apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-storage-binding
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: storageAccount
    value: "bmtestappa8da6"
  - name: storageAccessKey
    secretKeyRef:
      name: access-key
      key: access-key
  - name: queue
    value: "dapr"
  - name: ttlInSeconds
    value: "60"
auth:
  secretStore: my-secret-store