<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Component\Manager\Membership\Interface\Example001.Manager.Membership.Interface.csproj" />
    <ProjectReference Include="..\..\..\iFx\Hosting\Dapr\Example001.iFx.Hosting.Dapr.csproj" />
    <ProjectReference Include="..\..\..\iFx\Proxy\Example001.iFx.Proxy.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
