<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="NUnit.Analyzers" Version="3.6.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="SoEx.Test" Version="0.0.0-alpha-1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Component\Access\Entity\Service\Example101.Access.Entity.Service.csproj" />
    <ProjectReference Include="..\..\..\Component\Engine\Immitation\Service\Example101.Engine.Immitation.Service.csproj" />
    <ProjectReference Include="..\..\..\Component\Manager\Phenonmenon\Service\Example101.Manager.Phenonmenon.Service.csproj" />
    <ProjectReference Include="..\..\..\Common\Policy\Example101.Common.Policy.csproj" />
    <ProjectReference Include="..\..\..\Component\Utility\Cache\Service\Example101.Utility.Cache.Service.csproj" />
  </ItemGroup>

</Project>
