<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Interface\Example101.Engine.Immitation.Interface.csproj" />
    <ProjectReference Include="..\..\..\Access\Entity\Interface\Example101.Access.Entity.Interface.csproj" />
    <ProjectReference Include="..\..\..\..\iFx\Proxy\Example101.iFx.Proxy.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
