<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Interface\Example003.Manager.Membership.Interface.csproj" />
    <ProjectReference Include="..\..\..\..\iFx\Proxy\Example003.iFx.Proxy.csproj" />
    <ProjectReference Include="..\..\..\Access\Customer\Interface\Example003.Access.Customer.Interface.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
