<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.13" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\iFx\Hosting\InProc\Example101.iFx.Hosting.InProc.csproj" />
    <ProjectReference Include="..\..\Component\Access\Entity\Service\Example101.Access.Entity.Service.csproj" />
    <ProjectReference Include="..\..\Common\Policy\Example101.Common.Policy.csproj" />
    <ProjectReference Include="..\..\Component\Engine\Immitation\Service\Example101.Engine.Immitation.Service.csproj" />
    <ProjectReference Include="..\..\Component\Manager\Phenonmenon\Service\Example101.Manager.Phenonmenon.Service.csproj" />
    <ProjectReference Include="..\..\Component\Utility\Cache\Service\Example101.Utility.Cache.Service.csproj" />
    <ProjectReference Include="..\..\Component\Utility\Entitlement\Service\Example101.Utility.Entitlement.Service.csproj" />
    <ProjectReference Include="..\..\iFx\Service\Example101.iFx.Service.csproj" />
  </ItemGroup>

</Project>
