<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Interface\Example101.Manager.Phenonmenon.Interface.csproj" />
    <ProjectReference Include="..\..\..\Engine\Immitation\Interface\Example101.Engine.Immitation.Interface.csproj" />
    <ProjectReference Include="..\..\..\..\iFx\Proxy\Example101.iFx.Proxy.csproj" />
    <ProjectReference Include="..\..\..\Utility\Cache\Interface\Example101.Utility.Cache.Interface.csproj" />
    <ProjectReference Include="..\..\..\..\iFx\Service\Example101.iFx.Service.csproj" />
    <ProjectReference Include="..\..\..\..\Common\Contract\Example101.Common.Contract.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
